version: "3.1"
services:

    redis:
      image: redis:alpine
    mongo:
      container_name: junkrepo-mongodb
      build: ./docker/mongo
      ports:
        - "27017:27017"
      volumes:
        - ./mongo:/data/db
      networks:
        - backend

networks:
  backend:
    driver: "bridge"
